# Generated by Django 4.1.2 on 2022-10-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqrft',
            new_name='sqft',
        ),
    ]
