# Generated by Django 4.1.2 on 2022-10-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_sqrft_listing_sqft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_10',
            new_name='photo_main',
        ),
    ]
